services:
  mysql:
    image: bitnami/mysql:8.0
    healthcheck:
      test: "mysql --user=root --password=test1234 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - 8306:3306
    volumes:
      - ../../../docs/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - mysql_data_wa_scheduler:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_DATABASE=idnremotescheduler

  server-scheduler:
    build:
      context: ../../../
      dockerfile: ./build/package/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../../../cmd/web:/web
    environment:
      - LISTEN_PORT=${LISTEN_PORT:-9866}
      - MYSQL_DSN=${MYSQL_DSN:-root:test1234@tcp(mysql:3306)/idnremotescheduler?parseTime=true}
      - DASHBOARD_CLIENT_USERNAME=${DASHBOARD_CLIENT_USERNAME:-admin}
      - DASHBOARD_CLIENT_PASSWORD=${DASHBOARD_CLIENT_PASSWORD:-admin}
      - WA_DEFAULT_NUMBERS=${WA_DEFAULT_NUMBERS}
      - WA_PUBLISHER_API_BASE_URL=${WA_PUBLISHER_API_BASE_URL}
      - WA_PUBLISHER_USERNAME=${WA_PUBLISHER_USERNAME:-admin}
      - WA_PUBLISHER_PASSWORD=${WA_PUBLISHER_PASSWORD:-admin}
    ports:
      - "9866:9866"

volumes:
  mysql_data_wa_scheduler:
